Feat : add login auth & error handler
kor-kms/todo_fastapi pull request #2
Opened 2024-12-03 06:56 UTC by kor-kms

## 개발내용
- cryptography 를 사용하여 인증/인가 로직 구현
- 기본적인 HTTP Error Handler 생성
- 보안성을 위해 API 통신 로직 변경
  - user_id를 토큰값에서 추출하여 사용하도록 변경

2024-12-09 13:27 UTC, JunHCha requested changes
코멘트 확인 후 수정한 커밋번호를 각 코멘트의 답글로 남겨주세요!

2024-12-09 13:27 UTC, JunHCha commented on poetry.lock
pyproject.toml 파일과 poetry.lock 파일이 상이하여 `poetry install`을 실행할 시 오류가 납니다.
`poetry lock` 명령어를 실행해서 poetry.lock 파일을 최신화 해야 할 것 같아요!

<img width="910" alt="image" src="https://github.com/user-attachments/assets/070f57d2-b107-4ece-bc8f-ba1e4e3459cc">

2024-12-09 13:27 UTC, JunHCha commented on docker-compose.yml
> +      name: todo_fastapi_default
docker network의 external 옵션은, 서로 다른 compose 끼리 통신할때 사용할 외부 네트워크를 명시하는 부분으로, 관리자가 사전에 'todo_fastapi_default'라는 네트워크를 따로 구성해두어야 사용 가능합니다.
이 프로젝트의 경우, 아래처럼만 해두어도 자동으로 internal todo_fastapi_default 네트워크가 생성되어 문제없이 컨테이너를 띄울 수 있습니다.
```suggestion
networks:
  todo_fastapi_default:
```

2024-12-09 13:27 UTC, JunHCha commented on migrations/versions/732e50cd86fd_first.py
db/tables.py에 정의한 내용과 migration 파일이 일치하지 않습니다.
Fastapi container에서 `alembic revision --autogenerate` 명령어를 입력하면 현재 tables.py에 추가된 스냅샷을 생성할 수 있습니다.

```
root@c0e58ee7a4e1:/code# alembic revision --autogenerate
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.ddl.postgresql] Detected sequence named 'TB_USER_user_id_seq' as owned by integer column 'TB_USER(user_id)', assuming SERIAL and omitting
INFO  [alembic.ddl.postgresql] Detected sequence named 'TB_TODO_todo_id_seq' as owned by integer column 'TB_TODO(todo_id)', assuming SERIAL and omitting
INFO  [alembic.autogenerate.compare] Detected type change from TEXT() to String() on 'TB_TODO.context'
INFO  [alembic.autogenerate.compare] Detected NOT NULL on column 'TB_TODO.modified_at'
INFO  [alembic.autogenerate.compare] Detected added unique constraint None on '('user_id',)'
INFO  [alembic.autogenerate.compare] Detected type change from TEXT() to String() on 'TB_USER.id'
INFO  [alembic.autogenerate.compare] Detected type change from TEXT() to String() on 'TB_USER.pw'
INFO  [alembic.autogenerate.compare] Detected NOT NULL on column 'TB_USER.modified_at'
INFO  [alembic.autogenerate.compare] Detected added unique constraint None on '('id',)'
  Generating /code/migrations/versions/656a9e7ddd75_.py ...  done
root@c0e58ee7a4e1:/code# cat /code/migrations/versions/656a9e7ddd75_.py 
"""empty message

Revision ID: 656a9e7ddd75
Revises: 732e50cd86fd
Create Date: 2024-12-09 12:30:54.429892

"""shell
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '656a9e7ddd75'
down_revision: Union[str, None] = '732e50cd86fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TB_TODO', 'context',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('TB_TODO', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'TB_TODO', ['user_id'])
    op.alter_column('TB_USER', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('TB_USER', 'pw',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('TB_USER', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'TB_USER', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TB_USER', type_='unique')
    op.alter_column('TB_USER', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('TB_USER', 'pw',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('TB_USER', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'TB_TODO', type_='unique')
    op.alter_column('TB_TODO', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('TB_TODO', 'context',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
root@c0e58ee7a4e1:/code# 
```

alembic을 이용하는 이유는 db 스키마의 변경이력을 관리함과 동시에, revision autogenerate 기능을 활용하여 app에서 정의한 모델과 db 스키마를 일치시키는데에 그 목적이 있습니다.
따라서 alembic으로 app에서 정의된 모델과 db 상태를 동기화할 수 있는 환경 설정이 더 필요 합니다. (envs.py, alembic.ini 설정 등)

2024-12-09 13:27 UTC, JunHCha commented on app/db/session.py
> +            "postgresql+asyncpg://user:password@127.0.0.1:5432/todo",
FastAPI app을 도커 컨테이너로 띄울 경우 해당 주소로 DB 접속을 시도하면 에러가 발생합니다.
아래로 바꾸면 해결이 됩니다.

```suggestion
            "postgresql+asyncpg://user:password@db:5432/todo",
```

개발환경을 설정할때 local shell에서 app을 띄울지, docker에서 띄울지 결정하고, 정한 방법대로 설정을 통일하는게 혼동을 줄일 수 있을 것 같습니다!

2024-12-09 13:27 UTC, JunHCha commented on app/user/service.py
> +        )
get_token 로직을 아래와 같이 Service class의 private method로 리팩터링하는 건 어떨까요?(p3)
1. get_token은 depends로 주입될때 사용되는 함수가 아니고, 해당 서비스에서만 사용됩니다.
2. get_token은 내부에 await 하는 로직이 아니므로 코루틴(async)으로 선언할 이유가 없습니다.

```suggestion
        cipher_token = self._get_token(user.user_id)

        return UserLoginResponse(
            token=cipher_token,
            nickname=user.id,
        )

    def _get_token(self, id: str):
        token = bytes(f"{id}-Simple-token-{datetime.now()}", "utf-8")
        cipher_token = cipher_suite.encrypt(token)
        return cipher_token


```

2024-12-09 13:27 UTC, JunHCha commented on app/user/repository.py
> +        return result
의도하신 대로 쿼리가 잘 동작하는 것 확인했습니다! 👍👍👍

2024-12-09 13:27 UTC, JunHCha commented on app/user/repository.py
> +    async def findUser(self, id: str) -> str:
service에서도 메서드는 snake case를 채택했으니, 여기서도 포맷을 통일시켜주면 좋을 것 같아요! (p4)
```suggestion
    async def find_user(self, id: str) -> str:

```

2024-12-09 13:27 UTC, JunHCha commented on app/user/api.py
> +    return res
👍

2024-12-09 13:27 UTC, JunHCha commented on app/db/tables.py
> +    user_id: Mapped[int] = mapped_column(Integer, unique=True, nullable=False)
Todo의 user_id에 unique constraint을 적용하면 사용자는 하나의 todo만 생성할 수 있게 됩니다. 수정이 필요해보입니다. (P1)

2024-12-09 13:27 UTC, JunHCha commented on app/todo/api.py
> +@app_router.get("/todoinfo", response_model=GetTodoInfoList)
todo를 List view로 fetch하는 로직이므로 단순하게 `GET /todo`로 정의해도 좋을 것 같습니다! (p3)
```suggestion
@app_router.get("/todo", response_model=GetTodoInfoList)

```

2024-12-09 13:27 UTC, JunHCha commented on app/todo/api.py
> +@app_router.post("/regtodo", response_model=InsertTodoInfo, status_code=201)
REST에서 action은 HTTP method로 표현하는걸 권장하고 있습니다.
지금 todo API는 기본적인 CRUD 기능만 포함하므로, `POST /todo`로 endpoint를 지정해도 의미상 혼동이 없을 것 같습니다! (P2)
```suggestion
@app_router.post("/todo", response_model=InsertTodoInfo, status_code=201)

```

2024-12-09 13:27 UTC, JunHCha commented on app/todo/api.py
> +@app_router.post("/deltodo", response_model=DeleteTodoInfo)
```suggestion
@app_router.delete("/todo", response_model=DeleteTodoInfo)

```
위와 같은 논리로, 이는 `DELETE /todo`로 정의해도 충분해 보입니다!

2024-12-09 13:27 UTC, JunHCha commented on app/todo/service.py
> +        raise NotImplementedError
method를 snake_case로 통일하면 좋을 것 같습니다! (p4)
```suggestion
class BaseTodoService(abc.ABC):
    def __init__(self, repository: BaseTodoRepository) -> None:
        self.todo_repository = repository

    @abc.abstractmethod
    async def fetch_todo(self, user_id: int) -> list[TodoInfo]:
        raise NotImplementedError
    
    @abc.abstractmethod
    async def add_todo(self, user_id: int, context: str) -> TodoInfo:
        raise NotImplementedError

    @abc.abstractmethod
    async def remove_todo(self, user_id:int, todo_id: int) -> int:
        raise NotImplementedError

```

2024-12-09 13:27 UTC, JunHCha commented on app/todo/service.py
> +            raise NotFoundException
현재 로직에서는 '인가'에 대한 처리가 이루어지고 있지 않아서, 사용자가 만든 todo의 CRUD를 인가되지 않은 다른 사용자가 얼마든지 수행할 수 있는 취약점이 있습니다.
UserService에서 구현한 것처럼, 적절한 인가 로직이 Service에서 구현되어야 합니다! (p1)

2024-12-09 13:27 UTC, JunHCha commented on app/todo/repository.py
> +        result = await self.session.execute(delete(tb.Todo).where((tb.Todo.todo_id == todo_id) & (tb.Todo.user_id == user_id)))
```suggestion
        result = await self.session.execute(delete(tb.Todo).where(tb.Todo.todo_id == todo_id))

```

todo_id가 이미 unique하므로 user_id에 대한 condition이 없어도 의도된대로 동작할 것 같습니다! (p3)

2024-12-17 01:03 UTC, kor-kms commented on app/todo/repository.py
> +        result = await self.session.execute(delete(tb.Todo).where((tb.Todo.todo_id == todo_id) & (tb.Todo.user_id == user_id)))
혹시 모를 보안을 위해 해당 조건절을 추가했습니다.
만약 ROW의 user_id가 1일 때, user_id 가 1인 유저가 todo_id를 바꿔서 진행하면 해당 로직이 실행되기에
추가했습니다.

2024-12-17 01:05 UTC, kor-kms commented on app/todo/service.py
> +            raise NotFoundException
todo/api.ty의 user_id: int = Depends(get_current_user) 를 통해 인가를 진행합니다.
auth.py의 get_current_user 함수에서 토큰값을 해독할 수 없을 때 ForbiddenException 를 raise 시키도록 했습니다.

2024-12-17 01:07 UTC, kor-kms commented on app/user/repository.py
> +        return result
감사합니다 👍👍👍

2024-12-17 01:07 UTC, kor-kms commented on app/user/api.py
> +    return res
👍👍👍

2024-12-18 08:30 UTC, kor-kms commented on app/user/service.py
> +        )
현재 cipher_suite를 사용하는 함수가 get_current_user(인가 함수) 와 get_token(토큰생성 함수) 입니다.
cipher_suite를 사용하기 위해서는 secret_key 를 생성해야하는데 만약 auth.py와 user/service.py에서 생성을 하게되면 해당 값이 달라져 문제가 발생합니다. 하여, 위와 같이 auth.py에 생성 후 import 하여 사용했습니다.

2024-12-18 08:55 UTC, kor-kms commented on app/todo/api.py
> +@app_router.get("/todoinfo", response_model=GetTodoInfoList)
변경완료했습니다!
10fcdca476d40ccf1fd8c9d6a29a30c9f744a525

2024-12-18 08:55 UTC, kor-kms commented on app/todo/api.py
> +@app_router.post("/deltodo", response_model=DeleteTodoInfo)
변경완료했습니다!
10fcdca476d40ccf1fd8c9d6a29a30c9f744a525

2024-12-18 08:55 UTC, kor-kms commented on app/todo/api.py
> +@app_router.post("/regtodo", response_model=InsertTodoInfo, status_code=201)
변경완료했습니다!
10fcdca476d40ccf1fd8c9d6a29a30c9f744a525

2024-12-18 08:57 UTC, kor-kms commented on app/db/tables.py
> +    user_id: Mapped[int] = mapped_column(Integer, unique=True, nullable=False)
변경완료 했습니다!
a04e5fed5cf38989d43c79b2e48d51ff0d63a632

2024-12-18 09:03 UTC, kor-kms commented on app/user/repository.py
> +    async def findUser(self, id: str) -> str:
전체적으로 camel case to snake case 작업을 진행했습니다!
84c056e77b01e74ea77b230e5bea4efdd46f2e24

2024-12-25 03:23 UTC, JunHCha commented on docker-compose.yml
> +      name: todo_fastapi_default
구두리뷰로 해결했습니다~!

2024-12-25 03:23 UTC, JunHCha commented on migrations/versions/732e50cd86fd_first.py
구두리뷰로 해결했습니다~!

2024-12-25 03:24 UTC, JunHCha commented on app/db/session.py
> +            "postgresql+asyncpg://user:password@127.0.0.1:5432/todo",
구두리뷰로 해결했습니다~!

2024-12-25 03:24 UTC, JunHCha commented on poetry.lock
구두리뷰로 해결했습니다~!

2024-12-25 03:34 UTC, kor-kms commented
@JunHCha 리뷰 부탁드립니다.

2024-12-26 05:16 UTC, kor-kms commented
@JunHCha Delete 시 user 인가 관련 로직 수정했습니다.
리뷰 부탁드립니다!

2024-12-26 15:16 UTC, JunHCha approved these changes
LGTM 👍 고생하셨습니다! Merge 해주시면 됩니다!

### 좋았던 점: 
- FastAPI와 SQLAlchemy의 사용이 익숙하지 않으셨을 텐데, 배경지식이 탄탄하셔서 빠르게 아키텍처를 이해하시는 모습이 인상적이었습니다.
- 코드리뷰 가이드대로 건설적인 피드백이 오가는 데에 협조해주셔서 감사했습니다.

### 아쉬운 점
- 온보딩의 기간이 생각보다 많이 길어졌습니다. 제가 더 적극적으로 페어프로그래밍 약속을 잡았다면 더 효율적인 작업이 되었을 것 같습니다.
- 테스트코드 작성이 훈련이 많이 필요한 부분인데, 이번 온보딩에서 하지 못한 것이 조금 아쉬웠습니다.

2025-01-06 07:42 UTC, merged